name: Jekyll site CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install dependencies
      run: |
        gem install bundler -v 2.4.22
        bundle _2.4.22_ install

    - name: Build the site
      run: bundle exec jekyll build

    - name: HTML Validation
      continue-on-error: true
      run: |
        gem install html-proofer
        bundle exec htmlproofer ./_site --checks Images,Links,Scripts,OpenGraph,Favicon --url-swap "https://www.linkedin.com/in/nabil-el-bajdi-51726b24b/:#" || echo "HTML validation errors detected. Check the report above."

    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages
