name: Jekyll site CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.1'

    - name: Install dependencies
      run: |
        gem install bundler -v 2.4.22
        bundle _2.4.22_ install

    - name: Security Audit
      run: |
        bundle exec bundler-audit check --update || echo "Security vulnerabilities detected. Check the report above."

    - name: Build the site
      run: bundle exec jekyll build

    - name: Link Validation
      continue-on-error: true
      run: |
        gem install html-proofer
        bundle exec htmlproofer ./_site || echo "Link validation errors detected. Check the report above."

    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v8
      with:
        urls: 'https://nabilelbajdi.github.io/resume/'
        uploadArtifacts: true

    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages
